<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <h4 class="page-title">Welcome <?php echo $this->user->display_name ?>!</h4>
            <ol class="breadcrumb float-right">
                <li class="breadcrumb-item"><a href="#">Minton</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
            <div class="clearfix"></div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-lg-6 col-xl-3">
        <div class="widget-bg-color-icon card-box">
            <div class="bg-icon bg-icon-success pull-left">
                <i class="fa fa-thermometer-empty text-success"></i>
            </div>
            <div class="text-right">
                <h3 class="text-dark m-t-10"><b class="counter">17</b> &deg;</h3>
                <p class="text-muted mb-0">Temperature (Avg.)</p>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="col-lg-6 col-xl-3">
        <div class="widget-bg-color-icon card-box fadeInDown animated">
            <div class="bg-icon bg-icon-primary pull-left">
                <i class=" ti-money text-info"></i>
            </div>
            <div class="text-right">
                <h3 class="text-dark m-t-10"><b class="counter">31,570</b></h3>
                <p class="text-muted mb-0">Total Revenue</p>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="col-lg-6 col-xl-3">
        <div class="widget-bg-color-icon card-box">
            <div class="bg-icon bg-icon-danger pull-left">
                <i class="ti-shopping-cart text-pink"></i>
            </div>
            <div class="text-right">
                <h3 class="text-dark m-t-10"><b class="counter">280</b></h3>
                <p class="text-muted mb-0">Today's Sales</p>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="col-lg-6 col-xl-3">
        <div class="widget-bg-color-icon card-box">
            <div class="bg-icon bg-icon-purple pull-left">
                <i class="ti-stats-up text-purple"></i>
            </div>
            <div class="text-right">
                <h3 class="text-dark m-t-10"><b class="counter">0.16</b>%</h3>
                <p class="text-muted mb-0">Conversion</p>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!-- end row -->


<div class="row">
    <div class="col-lg-7">
        <div class="card-box">
            <h4 class="text-dark  header-title m-t-0 m-b-30">Total Revenue</h4>

            <div class="widget-chart text-center">
                <div id="dashboard-chart-1" style="height: 300px;"></div>

            </div>
        </div>

    </div>

    <div class="col-lg-5">
        <div class="card-box">
            <h4 class="text-dark  header-title m-t-0 m-b-30">Yearly Sales Report</h4>

            <div class="widget-chart text-center">
                <div id="morris-donut-example" style="height: 300px;"></div>

            </div>
        </div>

    </div>

</div>
<!-- end row -->



<div class="row">
    <div class="col-lg-8">
        <div class="card-box">
            <h4 class="text-dark  header-title m-t-0">Latest Measurements</h4>
            <p class="text-muted m-b-25 font-13">
                The latest measurements, the average per hour
            </p>

            <div class="table-responsive">
                <table class="table mb-0">
                    <thead>
                    <tr>
                        <th>Measure time</th>
                        <th>Location</th>
                        <th>Measurement</th>
                        <th>Humidity</th>
                        <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>20:10:52</td>
                        <td>Honduars North</td>
                        <td>17 &deg;</td>
                        <td>73 %</td>
                        <td><span class="badge badge-success">OK</span></td>
                    </tr>
                    <tr>
                        <td>20:10:49</td>
                        <td>Honduars West</td>
                        <td>16 &deg;</td>
                        <td>89 %</td>
                        <td><span class="badge badge-success">OK</span></td>
                    </tr>
                    <tr>
                        <td>20:10:41</td>
                        <td>Honduars East</td>
                        <td>16 &deg;</td>
                        <td>76 %</td>
                        <td><span class="badge badge-success">OK</span></td>
                    </tr>
                    <tr>
                        <td>20:10:38</td>
                        <td>Honduars South</td>
                        <td>18 &deg;</td>
                        <td>82 %</td>
                        <td><span class="badge badge-success">OK</span></td>
                    </tr>
                    <tr>
                        <td>20:10:35</td>
                        <td>Honduars North</td>
                        <td>17 &deg;</td>
                        <td>72 %</td>
                        <td><span class="badge badge-success">OK</span></td>
                    </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- end col -8 -->

    <div class="col-lg-4">

        <a href="mailto:niels.doornbos@softenco.com?subject=Support Request" style="color: #4c5667">
            <div class="card-box widget-user">
                <div>
                    <i class="fa fa-handshake-o float-left" style="font-size: 55px; margin-top: 10px"></i>
                    <div class="wid-u-info">
                        <h5 class="mt-0 m-b-5 font-16">Personal Solution Contact</h5>
                        <small class="text-success"><b>Niels Doornbos</b></small>

                        <p class="text-muted m-b-5 font-13">niels.doornbos@softenco.com</p>
                    </div>
                </div>
            </div>
        </a>

        <a href="mailto:redmar.bakker@softenco.com?subject=Support Request" style="color: #4c5667">
            <div class="card-box widget-user">
                <div>
                    <i class="fa fa-question-circle-o float-left" style="font-size: 80px; margin: -5px 0px;"></i>
                    <div class="wid-u-info">
                        <h5 class="mt-0 m-b-5 font-16">Web support</h5>
                        <small class="text-success"><b>Redmar Bakker</b></small>
                        <p class="text-muted m-b-5 font-13">redmar.bakker@softenco.com</p>
                    </div>
                </div>
            </div>
        </a>

        <a href="mailto:martin.vinke@softenco.com?subject=Support Request" style="color: #4c5667">
            <div class="card-box widget-user">
                <div>
                    <i class="fa fa-thermometer-empty float-left" style="font-size: 70px; margin-left: 16px"></i>
                    <div class="wid-u-info">
                        <h5 class="mt-0 m-b-5 font-16">Reliability Support</h5>
                        <small class="text-success"><b>Martin Vinke</b></small>
                        <p class="text-muted m-b-5 font-13">martin.vinke@softenco.com</p>
                    </div>
                </div>
            </div>
        </a>

        <a href="mailto:sander.van.doorn@softenco.com?subject=Support Request" style="color: #4c5667">
            <div class="card-box widget-user">
                <div>
                    <i class="fa fa-file-archive-o float-left" style="font-size: 70px; margin-left: 7px"></i>
                    <div class="wid-u-info">
                        <h5 class="mt-0 m-b-5 font-16">Data Support (Archive)</h5>
                        <small class="text-success"><b>Sander van Doorn</b></small>
                        <p class="text-muted m-b-5 font-13">sander.van.doorn@softenco.com</p>
                    </div>
                </div>
            </div>
        </a>

    </div>

</div>
<!-- end row -->