<link href="/plugins/sweet-alert/sweetalert2.min.css" rel="stylesheet" />
<link href="/plugins/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css">
<link href="/plugins/datatables/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css">

<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <h4 class="page-title">Departments</h4>
            <ol class="breadcrumb float-right">
                <li class="breadcrumb-item"><a href="#">Lacthosa</a></li>
                <li class="breadcrumb-item active">Departments</li>
            </ol>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="card-box">
            <span class="pull-right text-dark"><small>UPDATED:</small> 20:10:52</span>
            <h4 class="text-dark header-title m-t-0">Department Measurements</h4>
            <p class="text-muted m-b-25 font-13">
                The latest measurements, grouped by department
            </p>

            <div class="table-responsive">
                <table class="table table-striped table-bordered mb-0" id="datatable-buttons">
                    <thead>
                    <tr>
                        <th>Department</th>
                        <th>Temperature</th>
                        <th>Humidity</th>
                        <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Department 1</td>
                            <td>17 &deg;</td>
                            <td>73 %</td>
                            <td><span class="badge badge-success">OK</span></td>
                        </tr>
                        <tr>
                            <td>Department 2</td>
                            <td>16 &deg;</td>
                            <td>89 %</td>
                            <td><span class="badge badge-success">OK</span></td>
                        </tr>
                        <tr>
                            <td>Department 3</td>
                            <td>16 &deg;</td>
                            <td>76 %</td>
                            <td><span class="badge badge-success">OK</span></td>
                        </tr>
                        <tr>
                            <td>Department 4</td>
                            <td>18 &deg;</td>
                            <td>82 %</td>
                            <td><span class="badge badge-success">OK</span></td>
                        </tr>
                        <tr>
                            <td>Department 5</td>
                            <td>17 &deg;</td>
                            <td>73 %</td>
                            <td><span class="badge badge-success">OK</span></td>
                        </tr>
                        <tr>
                            <td>Department 6</td>
                            <td>16 &deg;</td>
                            <td>89 %</td>
                            <td><span class="badge badge-success">OK</span></td>
                        </tr>
                        <tr>
                            <td>Department 7</td>
                            <td>16 &deg;</td>
                            <td>76 %</td>
                            <td><span class="badge badge-success">OK</span></td>
                        </tr>
                        <tr>
                            <td>Department 8</td>
                            <td>18 &deg;</td>
                            <td>82 %</td>
                            <td><span class="badge badge-success">OK</span></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- end col -8 -->

</div>
<!-- end row -->

<?php \App\LayoutModel::appendScript('/plugins/sweet-alert/sweetalert2.min.js') ?>
<?php \App\LayoutModel::appendScript('/plugins/datatables/jquery.dataTables.min.js') ?>
<?php \App\LayoutModel::appendScript('/plugins/datatables/dataTables.bootstrap4.min.js') ?>
<?php \App\LayoutModel::appendScript('/plugins/datatables/dataTables.buttons.min.js') ?>
<?php \App\LayoutModel::appendScript('/assets/pages/jquery.departments.js') ?>