<link href="/plugins/jvectormap/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
<link href="/plugins/sweet-alert/sweetalert2.min.css" rel="stylesheet" />

<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <h4 class="page-title">Map</h4>
            <ol class="breadcrumb float-right">
                <li class="breadcrumb-item"><a href="#">Lacthosa</a></li>
                <li class="breadcrumb-item active">Map</li>
            </ol>
            <div class="clearfix"></div>
        </div>
    </div>
</div>


<div class="row">

    <div class="col-lg-12">
        <div class="card-box">
            <h4 class="header-title m-t-0">Station Visualisation Honduras</h4>
            <p class="text-muted m-b-10 font-13" style="border-bottom: 1px solid #eee; padding-bottom:10px;">
                Real-time visualisation of Honduras. Provided with temperature and humidity over stations.
            </p>
            <div id="map-markers" style="height: 500px;"></div>
        </div>
    </div>

</div>
<!-- end row -->

<?php \App\LayoutModel::appendScript('/plugins/jvectormap/jquery-jvectormap-2.0.2.min.js') ?>
<?php \App\LayoutModel::appendScript('/plugins/jvectormap/jquery-jvectormap-north_america-mill.js') ?>
<?php \App\LayoutModel::appendScript('/plugins/sweet-alert/sweetalert2.min.js') ?>
<?php \App\LayoutModel::appendScript('/assets/pages/jquery.map.js') ?>