<div class="text-center">
    <a href="/" class="logo-lg">
        <img src="/img/logo.png" alt="Logo" height="40px">
    </a>
</div>

<form method="post" action="/auth/login" role="form" class="text-center m-t-20">
    <div class="user-thumb">
        <img src="/assets/images/users/avatar-2.jpg" class="rounded-circle img-thumbnail" alt="thumbnail">
    </div>
    <div class="form-group">
        <h5 class="text-uppercase mt-2"><?php echo $this->user->display_name ?></h5>
        <p class="text-muted">Enter your password to access the admin.</p>
        <div class="input-group m-t-30">
            <input type="hidden" class="form-control" name="username" value="<?php echo $this->user->username ?>">
            <input type="password" class="form-control" name="password" placeholder="Password">
            <i class="md md-vpn-key form-control-feedback l-h-34" style="left:6px;z-index: 99;"></i>
            <span class="input-group-append">
                <button type="submit" class="btn btn-email btn-primary waves-effect waves-light"> Log In </button>
            </span>
        </div>
    </div>
    <div class="text-right">
        <a href="/auth/login" class="text-muted">Not <?php echo $this->user->display_name ?>?</a>
    </div>
</form>