<div class="text-center">
    <a href="/" class="logo-lg">
        <img src="/img/logo.png" alt="Logo" height="40px">
    </a>
</div>


<?php if (@$this->valid === false): ?>
    <p style="color: red; border: 1px solid grey; border-radius: .25rem; padding: 10px; margin-top: 16px">
        The credentials did not match an existing account.
    </p>
<?php endif; ?>

<form class="form-horizontal m-t-20" action="#" method="POST">

    <div class="form-group row">
        <div class="col-12">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="mdi mdi-account"></i></span>
                </div>
                <input class="form-control" type="text" required="" name="username" placeholder="Username">
            </div>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-12">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="mdi mdi-radar"></i></span>
                </div>
                <input class="form-control" type="password" required="" name="password" placeholder="Password">
            </div>
        </div>
    </div>


    <div class="form-group text-right m-t-20">
        <div class="col-xs-12">
            <button class="btn btn-primary btn-custom w-md waves-effect waves-light" type="submit">Log In
            </button>
        </div>
    </div>
</form>