<?php /** @var $this \App\LayoutModel */ ?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
    <meta name="author" content="Coderthemes">

    <link rel="shortcut icon" href="/assets/images/favicon.ico">

    <title>Lacthosa - Management</title>

    <link href="/plugins/switchery/switchery.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="/plugins/morris/morris.css">

    <link href="/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/css/icons.css" rel="stylesheet" type="text/css">
    <link href="/assets/css/style.css" rel="stylesheet" type="text/css">

    <script src="/assets/js/modernizr.min.js"></script>


    <script>

        var USER_TOKEN = "<?php echo $this->user->getToken() ?>";

    </script>
</head>

<body class="fixed-left">

    <!-- Begin page -->
    <div id="wrapper">

        <?php echo $this->header() ?>

        <?php echo $this->sideMenu() ?>


        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="content-page">
            <!-- Start content -->
            <div class="content">
                <div class="container-fluid">

                    <?php echo $this->content ?>

                </div>
                <!-- end container -->
            </div>
            <!-- end content -->

            <footer class="footer">
                <?php echo date('Y') ?> &copy; Softenco B.V. - <a href="https://www.softenco.com/" style="color: #fff;">Softenco.com</a>
            </footer>

        </div>
        <!-- ============================================================== -->
        <!-- End Right content here -->
        <!-- ============================================================== -->


        <!-- Right Sidebar -->
        <div class="side-bar right-bar">
            <div class="">
                <ul class="nav nav-tabs tabs-bordered nav-justified">
                    <li class="nav-item">
                        <a href="#home-2" class="nav-link active" data-toggle="tab" aria-expanded="false">
                            Activity
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#messages-2" class="nav-link" data-toggle="tab" aria-expanded="true">
                            Settings
                        </a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="home-2">
                        <div class="timeline-2">
                            <div class="time-item">
                                <div class="item-info">
                                    <small class="text-muted">5 minutes ago</small>
                                    <p><strong><a href="#" class="text-info">John Doe</a></strong> Uploaded a photo <strong>"DSC000586.jpg"</strong>
                                    </p>
                                </div>
                            </div>

                            <div class="time-item">
                                <div class="item-info">
                                    <small class="text-muted">30 minutes ago</small>
                                    <p><a href="#" class="text-info">Lorem</a> commented your post.</p>
                                    <p><em>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam laoreet tellus
                                            ut tincidunt euismod. "</em></p>
                                </div>
                            </div>

                            <div class="time-item">
                                <div class="item-info">
                                    <small class="text-muted">59 minutes ago</small>
                                    <p><a href="#" class="text-info">Jessi</a> attended a meeting with<a href="#"
                                                                                                         class="text-success">John
                                            Doe</a>.</p>
                                    <p><em>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam laoreet tellus
                                            ut tincidunt euismod. "</em></p>
                                </div>
                            </div>

                            <div class="time-item">
                                <div class="item-info">
                                    <small class="text-muted">1 hour ago</small>
                                    <p><strong><a href="#" class="text-info">John Doe</a></strong>Uploaded 2 new photos</p>
                                </div>
                            </div>

                            <div class="time-item">
                                <div class="item-info">
                                    <small class="text-muted">3 hours ago</small>
                                    <p><a href="#" class="text-info">Lorem</a> commented your post.</p>
                                    <p><em>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam laoreet tellus
                                            ut tincidunt euismod. "</em></p>
                                </div>
                            </div>

                            <div class="time-item">
                                <div class="item-info">
                                    <small class="text-muted">5 hours ago</small>
                                    <p><a href="#" class="text-info">Jessi</a> attended a meeting with<a href="#"
                                                                                                         class="text-success">John
                                            Doe</a>.</p>
                                    <p><em>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam laoreet tellus
                                            ut tincidunt euismod. "</em></p>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="tab-pane" id="messages-2">

                        <div class="row m-t-20">
                            <div class="col-8">
                                <h5 class="m-0 font-15">Notifications</h5>
                                <p class="text-muted m-b-0">
                                    <small>Do you need them?</small>
                                </p>
                            </div>
                            <div class="col-4 text-right">
                                <input type="checkbox" checked data-plugin="switchery" data-color="#3bafda"
                                       data-size="small"/>
                            </div>
                        </div>

                        <div class="row m-t-20">
                            <div class="col-8">
                                <h5 class="m-0 font-15">API Access</h5>
                                <p class="m-b-0 text-muted">
                                    <small>Enable/Disable access</small>
                                </p>
                            </div>
                            <div class="col-4 text-right">
                                <input type="checkbox" checked data-plugin="switchery" data-color="#3bafda"
                                       data-size="small"/>
                            </div>
                        </div>

                        <div class="row m-t-20">
                            <div class="col-8">
                                <h5 class="m-0 font-15">Auto Updates</h5>
                                <p class="m-b-0 text-muted">
                                    <small>Keep up to date</small>
                                </p>
                            </div>
                            <div class="col-4 text-right">
                                <input type="checkbox" checked data-plugin="switchery" data-color="#3bafda"
                                       data-size="small"/>
                            </div>
                        </div>

                        <div class="row m-t-20">
                            <div class="col-8">
                                <h5 class="m-0 font-15">Online Status</h5>
                                <p class="m-b-0 text-muted">
                                    <small>Show your status to all</small>
                                </p>
                            </div>
                            <div class="col-4 text-right">
                                <input type="checkbox" checked data-plugin="switchery" data-color="#3bafda"
                                       data-size="small"/>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- /Right-bar -->

    </div>
    <!-- END wrapper -->

    <script src=""></script>

    <script>
        var resizefunc = [];

        process = {
            env: {
                NODE_ENV: "development"
            }
        };

    </script>

    <!-- Plugins  -->
    <?php \App\LayoutModel::appendScript('/assets/js/jquery.min.js', -200) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/popper.min.js', -200) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/bootstrap.min.js', -200) ?>
    <?php \App\LayoutModel::appendScript('https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js', -200) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/babel.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/detect.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/fastclick.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/jquery.slimscroll.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/jquery.blockUI.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/waves.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/wow.min.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/jquery.nicescroll.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/jquery.scrollTo.min.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/plugins/switchery/switchery.min.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/socket.sdk.js', -150) ?>

    <!-- Counter Up  -->
    <?php \App\LayoutModel::appendScript('/plugins/waypoints/lib/jquery.waypoints.min.js', -100) ?>
    <?php \App\LayoutModel::appendScript('/plugins/counterup/jquery.counterup.min.js', -100) ?>

    <!--Morris Chart-->
    <?php \App\LayoutModel::appendScript('/plugins/morris/morris.min.js', -50) ?>
    <?php \App\LayoutModel::appendScript('/plugins/raphael/raphael-min.js', -50) ?>

    <!-- Custom main Js -->
    <?php \App\LayoutModel::appendScript('/assets/js/jquery.core.js', 100) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/jquery.app.js', 100) ?>

    <?php echo $this->scripts(); ?>

    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $('.counter').counterUp({
                delay: 100,
                time: 1200
            });
        });
    </script>

</body>
</html>