<?php /** @var $this \App\LayoutModel */ ?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
    <meta name="author" content="Coderthemes">

    <link rel="shortcut icon" href="/assets/images/favicon.ico">

    <title>Lacthosa - Management</title>

    <link href="/plugins/switchery/switchery.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="/plugins/morris/morris.css">

    <link href="/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/css/icons.css" rel="stylesheet" type="text/css">
    <link href="/assets/css/style.css" rel="stylesheet" type="text/css">
    <link href="/assets/css/pace.css" rel="stylesheet" type="text/css">

    <script src="/assets/js/modernizr.min.js"></script>
    <script src="/assets/js/pace.min.js"></script>


    <script>

        var USER_TOKEN = "<?php echo $this->user->getToken() ?>";

    </script>
</head>

<body class="fixed-left">

    <!-- Begin page -->
    <div id="wrapper">

        <?php echo $this->header() ?>

        <?php echo $this->sideMenu() ?>


        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="content-page">
            <!-- Start content -->
            <div class="content">
                <div class="container-fluid">

                    <?php echo $this->content ?>

                </div>
                <!-- end container -->
            </div>
            <!-- end content -->

            <footer class="footer">
                <?php echo date('Y') ?> &copy; Softenco B.V. - <a href="https://www.softenco.com/" style="color: #fff;">Softenco.com</a>
            </footer>

        </div>
        <!-- ============================================================== -->
        <!-- End Right content here -->
        <!-- ============================================================== -->


        <!-- Right Sidebar -->
        <div id="side-bar"></div>
        <!-- /Right-bar -->

    </div>
    <!-- END wrapper -->

    <script>
        var resizefunc = [];

        process = {
            env: {
                NODE_ENV: "development"
            }
        };

    </script>

    <!-- Plugins  -->
    <?php \App\LayoutModel::appendScript('/assets/js/jquery.min.js', -200) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/popper.min.js', -200) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/bootstrap.min.js', -200) ?>
    <?php \App\LayoutModel::appendScript('https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js', -200) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/babel.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/detect.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/fastclick.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/jquery.slimscroll.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/jquery.blockUI.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/waves.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/wow.min.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/jquery.nicescroll.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/jquery.scrollTo.min.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/plugins/switchery/switchery.min.js', -150) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/moment.js', -150) ?>

    <?php \App\LayoutModel::appendScript('https://unpkg.com/react@16/umd/react.development.js', -150) ?>
    <?php \App\LayoutModel::appendScript('https://unpkg.com/react-dom@16/umd/react-dom.development.js', -150) ?>
    <?php \App\LayoutModel::appendScript('https://cdnjs.cloudflare.com/ajax/libs/rxjs/6.4.0/rxjs.umd.min.js', -150) ?>

    <?php \App\LayoutModel::appendScript('/assets/js/socket.sdk.js', -150) ?>

    <!-- Counter Up  -->
    <?php \App\LayoutModel::appendScript('/plugins/waypoints/lib/jquery.waypoints.min.js', -100) ?>
    <?php \App\LayoutModel::appendScript('/assets/components/side-bar.component.js', -100, 'text/babel') ?>
    <?php \App\LayoutModel::appendScript('/assets/js/jquery.layout.js', -100, 'text/babel') ?>

    <!--Morris Chart-->
    <?php \App\LayoutModel::appendScript('/plugins/morris/morris.min.js', -50) ?>
    <?php \App\LayoutModel::appendScript('/plugins/raphael/raphael-min.js', -50) ?>

    <!-- Custom main Js -->
    <?php \App\LayoutModel::appendScript('/assets/js/jquery.core.js', 100) ?>
    <?php \App\LayoutModel::appendScript('/assets/js/jquery.app.js', 100) ?>

    <?php echo $this->scripts(); ?>

</body>
</html>