<!-- ========== Left Sidebar Start ========== -->

<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <!--- Divider -->
        <div id="sidebar-menu">
            <ul>
                <li class="menu-title">Main</li>

                <li>
                    <a href="/dashboard" class="waves-effect waves-primary">
                        <i class="ti-home"></i><span> Dashboard </span>
                    </a>
                </li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect waves-primary">
                        <i class="ti-shine"></i><span> Apps </span>
                        <span class="badge badge-pink pull-right">New</span>
                    </a>
                    <ul class="list-unstyled">
                        <li><a href="apps-kanban.html">Kanban Board</a></li>
                        <li><a href="apps-companies.html">Companies</a></li>
                        <li><a href="apps-filemanager.html">File Manager</a></li>
                        <li><a href="apps-tickets.html">Tickets</a></li>
                        <li><a href="apps-calendar.html">Calendar</a></li>
                        <li><a href="apps-team.html">Team Members</a></li>
                    </ul>
                </li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect waves-primary">
                        <i class="ti-email"></i><span> Mail </span>
                        <span class="menu-arrow"></span>
                    </a>
                    <ul class="list-unstyled">
                        <li><a href="mail-inbox.html">Inbox</a></li>
                        <li><a href="mail-compose.html">Compose Mail</a></li>
                        <li><a href="mail-read.html">View Mail</a></li>
                    </ul>
                </li>
            </ul>

            <div class="clearfix"></div>
        </div>

        <footer class="sidebar-menu-footer">
            &nbsp;
            <a href="#" onclick="$('#sidebar-chevron').toggleClass('fa-chevron-left').toggleClass('fa-chevron-right');" class="open-left">
                <span class="fa fa-chevron-left float-right" id="sidebar-chevron"></span>
            </a>
        </footer>

        <div class="clearfix"></div>
    </div>
</div>
<!-- Left Sidebar End -->