<!-- ========== Left Sidebar Start ========== -->

<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <!--- Divider -->
        <div id="sidebar-menu">

            <ul>
                <li class="menu-title">Main</li>
                <li>
                    <a href="/dashboard" class="waves-effect waves-primary">
                        <i class="ti-home"></i><span> Dashboard </span>
                    </a>
                </li>
                <li>
                    <a href="/map" class="waves-effect waves-primary">
                        <i class="ti-location-pin"></i><span> Map</span>
                    </a>
                </li>
            </ul>

            <ul>
                <li class="menu-title">Resources</li>
                <li>
                    <a href="/departments" class="waves-effect waves-primary">
                        <i class="ti-direction"></i><span> Departments</span>
                    </a>
                </li>
                <li>
                    <a href="/stations" class="waves-effect waves-primary">
                        <i class="ti-location-arrow"></i><span> Stations</span>
                    </a>
                </li>
            </ul>

            <div class="clearfix"></div>
        </div>

        <footer class="sidebar-menu-footer">
            &nbsp;
            <a href="#" onclick="$('#sidebar-chevron').toggleClass('fa-chevron-left').toggleClass('fa-chevron-right');" class="open-left">
                <span class="fa fa-chevron-left float-right" id="sidebar-chevron"></span>
            </a>
        </footer>

        <div class="clearfix"></div>
    </div>
</div>
<!-- Left Sidebar End -->